/**
 * claude.js - Claude API helpers
 *
 * Three distinct calls:
 *  1. classifyMessage  - cheap yes/no classification
 *  2. analyzePlan      - full analysis (proposed_changes + manual_steps)
 *  3. refinePlan       - refinement based on user feedback
 */

import Anthropic from '@anthropic-ai/sdk';

const MODEL = 'claude-sonnet-4-6';

// ─────────────────────────────────────────────
// 1. CLASSIFY
// ─────────────────────────────────────────────

/**
 * Returns true if the Slack message appears to be a weekly service plan.
 */
export async function classifyMessage(messageText, apiKey) {
  const client = new Anthropic({ apiKey });

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 10,
    messages: [
      {
        role: 'user',
        content: `Does this Slack message appear to be a weekly church service plan update that describes what is happening in an upcoming Sunday service, including service elements, notices, or instructions for the team? Reply with just "yes" or "no".

Message:
${messageText}`,
      },
    ],
  });

  const answer = response.content[0]?.text?.trim().toLowerCase() ?? 'no';
  return answer === 'yes';
}

// ─────────────────────────────────────────────
// 2. FULL ANALYSIS
// ─────────────────────────────────────────────

/**
 * Analyses the Slack plan message against the PCO plan.
 *
 * Returns:
 * {
 *   proposed_changes: [...],
 *   manual_steps: [...],
 *   roster_issues: [...]   // (passed through from pcoPlan, not generated by Claude)
 * }
 */
export async function analyzePlan(slackMessage, pcoPlan, apiKey) {
  const client = new Anthropic({ apiKey });

  const systemPrompt = buildAnalysisSystemPrompt();
  const userPrompt = buildAnalysisUserPrompt(slackMessage, pcoPlan);

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const raw = response.content[0]?.text ?? '{}';
  const parsed = parseJsonResponse(raw);

  return {
    proposed_changes: parsed.proposed_changes ?? [],
    manual_steps: parsed.manual_steps ?? [],
    roster_issues: pcoPlan.roster_issues ?? [],
  };
}

// ─────────────────────────────────────────────
// 3. REFINEMENT
// ─────────────────────────────────────────────

/**
 * Refines the plan based on user feedback posted in the Slack thread.
 *
 * @param {string} feedbackText   - The user's reply text
 * @param {object} storedState    - The current KV state (includes proposed_changes, manual_steps)
 * @param {object} pcoPlan        - Current PCO plan (for context)
 * @param {string} apiKey
 */
export async function refinePlan(feedbackText, storedState, pcoPlan, apiKey) {
  const client = new Anthropic({ apiKey });

  const systemPrompt = buildRefinementSystemPrompt();
  const userPrompt = buildRefinementUserPrompt(feedbackText, storedState, pcoPlan);

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const raw = response.content[0]?.text ?? '{}';
  const parsed = parseJsonResponse(raw);

  return {
    proposed_changes: parsed.proposed_changes ?? storedState.proposed_changes,
    manual_steps: parsed.manual_steps ?? storedState.manual_steps,
    roster_issues: pcoPlan.roster_issues ?? [],
  };
}

// ─────────────────────────────────────────────
// PROMPT BUILDERS
// ─────────────────────────────────────────────

function buildAnalysisSystemPrompt() {
  return `You are an assistant that helps manage a church service plan.
You receive a Slack message describing the upcoming Sunday service plan, plus the current state
of that plan in Planning Center Online (PCO).

Your job is to identify changes that should be made to the PCO plan and flag anything that
requires manual attention.

Automated rules you must apply:
1. Notice title fix: If an item is titled "Notice 1", "Notice 2", or "Notice 3" and its
   description starts with a real title on the first line, propose moving that first line to
   the item title and removing it from the description.
2. Empty notice removal: If a "Notice 1/2/3" item has no description, check whether ALL
   notices are empty. If ALL notices are empty, this means the communications person has not
   yet filled them in — do not propose deletion, instead add a manual step:
   "All notices are empty — check that the communications person has finalised the notices
   before Sunday." If only SOME notices are empty (others have descriptions), propose
   deleting only the empty ones.
3. Empty highlight removal: If a "Highlight" item has no content, propose deleting it.
4. Pray-er placeholder: If an item titled "Prayer" has a [...] placeholder in its
   description, propose replacing only the [...] with the volunteer assigned to the
   "Pray-er" role. Leave the rest of the description exactly as-is.
5. Bible reading placeholder: If an item's description contains a [...] placeholder and the
   item is a bible reading, propose replacing only the [...] with the volunteer assigned to
   the "Bible Reader" role. Leave the rest of the description exactly as-is.
6. Sermon placeholder: If an item's description contains a [...] placeholder and the item is
   a sermon, propose replacing only the [...] with the volunteer assigned to the "Preacher"
   role. Leave the rest of the description exactly as-is.

For fill_placeholder changes, new_description must be the full description with the [...]
replaced by the volunteer name — do not omit any other text that was already in the description.

Return ONLY a JSON object in this exact shape — no markdown, no explanation:
{
  "proposed_changes": [
    {
      "type": "notice_title",
      "item_id": "123",
      "item_title": "Notice 1",
      "new_title": "Explaining Christianity",
      "description_remainder": "..."
    },
    {
      "type": "remove_empty_notice",
      "item_id": "456",
      "item_title": "Notice 2"
    },
    {
      "type": "remove_empty_highlight",
      "item_id": "789",
      "item_title": "Highlight"
    },
    {
      "type": "fill_placeholder",
      "item_id": "101",
      "item_title": "Prayer",
      "role": "Pray-er",
      "team": "upfront",
      "volunteer_name": "John Smith",
      "new_description": "John Smith will be leading us in prayer today."
    }
  ],
  "manual_steps": [
    "Baptism segment mentioned in Slack message - unclear where this belongs in the plan."
  ]
}`;
}

function buildAnalysisUserPrompt(slackMessage, pcoPlan) {
  const itemsText = pcoPlan.items
    .map((item) =>
      `  ID: ${item.id}
  Title: ${item.attributes?.title ?? '(none)'}
  Description: ${item.attributes?.description ?? '(none)'}
  Type: ${item.attributes?.item_type ?? 'unknown'}`)
    .join('\n\n');

  const teamsText = pcoPlan.teams
    .map((team) => {
      const members = team.members
        .map((m) => `    - ${m.name} (${m.role}) — ${m.status}`)
        .join('\n');
      return `  Team: ${team.name}\n${members}`;
    })
    .join('\n\n');

  return `## Slack Service Plan Message

${slackMessage}

## PCO Plan: ${pcoPlan.title} (${pcoPlan.sort_date})

### Items
${itemsText}

### Teams
${teamsText}

Analyse the above and return the JSON object of proposed changes and manual steps.`;
}

function buildRefinementSystemPrompt() {
  return `You are an assistant helping refine a church service plan change proposal.
You have the current list of proposed changes and the user's feedback.
Update the proposed_changes and manual_steps based on the feedback.
Return ONLY a JSON object in the same shape as before — no markdown, no explanation:
{
  "proposed_changes": [...],
  "manual_steps": [...]
}`;
}

function buildRefinementUserPrompt(feedbackText, storedState, pcoPlan) {
  const currentPlan = JSON.stringify(
    {
      proposed_changes: storedState.proposed_changes,
      manual_steps: storedState.manual_steps,
    },
    null,
    2,
  );

  const itemsText = pcoPlan.items
    .map((item) =>
      `  ID: ${item.id} | Title: ${item.attributes?.title ?? '(none)'} | Desc: ${item.attributes?.description ?? '(none)'}`)
    .join('\n');

  return `## Current Proposed Changes
${currentPlan}

## PCO Items (for reference)
${itemsText}

## User Feedback
${feedbackText}

Update the plan based on the feedback and return the revised JSON.`;
}

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

function parseJsonResponse(text) {
  // Strip markdown code fences if Claude wraps its response
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch {
    console.error('Failed to parse Claude JSON response:', cleaned);
    return {};
  }
}
